### ISSUE TITLE
Code generator not handling fields with custom adapter

### ISSUE THREAD

**Issue by huehodaniel** [avaje/avaje-jsonb#381]
Using avaje-jsonb-generator 3.4 with Java 24.

I'm trying to use the `@Json` annotation to generate an adapter for a plain POJO that includes objects of complex classes with hand-made adapters annotated with `@CustomAdapter`, but the processor is trying to generate another adapter and failing. Minimal example:

```java
// Example.java
package org.hueho.issue;

import io.avaje.jsonb.Json;

@Json
public class Example {
    private int code;
    private WrapMap map;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public WrapMap getMap() {
        return map;
    }

    public void setMap(WrapMap map) {
        this.map = map;
    }
}
```

```java
// WrapMap.java
package org.hueho.issue;

import java.util.*;

public class WrapMap extends AbstractMap<String, String> {
    private final Map<String, String> delegate;

    public WrapMap(Map<String, String> map) {
        delegate = map;
    }

    @Override
    public Set<Entry<String, String>> entrySet() {
        return delegate.entrySet();
    }
}
```

```java
// WrapMapJsonAdapter.java
package org.hueho.issue;

import io.avaje.json.JsonAdapter;
import io.avaje.json.JsonReader;
import io.avaje.json.JsonWriter;
import io.avaje.jsonb.CustomAdapter;
import io.avaje.jsonb.Jsonb;
import io.avaje.jsonb.Types;

import java.util.Map;

@CustomAdapter
public class WrapMapJsonAdapter implements JsonAdapter<WrapMap> {
    private final JsonAdapter<Map<String, String>> stringMapJsonAdapter;

    public WrapMapJsonAdapter(Jsonb jsonb) {
        this.stringMapJsonAdapter = jsonb.adapter(Types.newParameterizedType(Map.class, String.class, String.class));
    }

    @Override
    public WrapMap fromJson(JsonReader reader) {
        return new WrapMap(stringMapJsonAdapter.fromJson(reader));
    }

    @Override
    public void toJson(JsonWriter writer, WrapMap wrapMap) {
        writer.beginObject();
        wrapMap.forEach((key, value) -> {
            writer.name(key);
            writer.value(value);
        });
        writer.endObject();
    }
}
```

Maven truncated output:
```
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 19 source files with javac [debug target 24] to target\classes
[INFO] org.hueho.issue.WrapMap, non accessible field delegate
[INFO] Skipped writing JsonAdapter for org.hueho.issue.WrapMap due to non accessible fields
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] org.hueho.issue.WrapMap, non public field delegate with no matching setter or constructor?
```

Note that the issue also happens if I annotate the `Example#map` field with `@Json.Serialize` and change the `@CustomAdapter` annotation to use `global = false`.

**Comment by SentryMan** [comment]
how interesting

**Comment by SentryMan** [comment]
does it work on 3.3?

**Comment by huehodaniel** [comment]
It doesn't work on any 3.x release.

It did work on 2.4 - it generated the expected adapter:

```java
@Generated("io.avaje.jsonb.generator")
public final class ExampleJsonAdapter implements JsonAdapter<Example>, ViewBuilderAware {

  // naming convention Match
  // code [int] name:code setter:setCode 
  // map [org.hueho.issue.WrapMap] name:map setter:setMap 

  private final JsonAdapter<Integer> pintJsonAdapter;
  private final JsonAdapter<WrapMap> wrapMapJsonAdapter;
  private final PropertyNames names;

  public ExampleJsonAdapter(Jsonb jsonb) {
    this.pintJsonAdapter = jsonb.adapter(Integer.TYPE);
    this.wrapMapJsonAdapter = jsonb.adapter(WrapMap.class);
    this.names = jsonb.properties("code", "map");
  }

  @Override
  public boolean isViewBuilderAware() {
    return true;
  }

  @Override
  public ViewBuilderAware viewBuild() {
    return this;
  }

  @Override
  public void build(ViewBuilder builder, String name, MethodHandle handle) {
    builder.beginObject(name, handle);
    builder.add("code", pintJsonAdapter, builder.method(Example.class, "getCode", int.class));
    builder.add("map", wrapMapJsonAdapter, builder.method(Example.class, "getMap", org.hueho.issue.WrapMap.class));
    builder.endObject();
  }

  @Override
  public void toJson(JsonWriter writer, Example example) {
    writer.beginObject(names);
    writer.name(0);
    pintJsonAdapter.toJson(writer, example.getCode());
    writer.name(1);
    wrapMapJsonAdapter.toJson(writer, example.getMap());
    writer.endObject();
  }

  @Override
  public Example fromJson(JsonReader reader) {
    Example _$example = new Example();

    // read json
    reader.beginObject(names);
    while (reader.hasNextField()) {
      final String fieldName = reader.nextField();
      switch (fieldName) {
        case "code": 
          _$example.setCode(pintJsonAdapter.fromJson(reader));
          break;

        case "map": 
          _$example.setMap(wrapMapJsonAdapter.fromJson(reader));
          break;

        default:
          reader.unmappedField(fieldName);
          reader.skipValue();
      }
    }
    reader.endObject();

    return _$example;
  }
}
```

**Comment by huehodaniel** [comment]
I'm sorry, something went wrong on my environment, it's only 3.4 that's not generating correctly, 3.3 and before are working fine.

**Comment by huehodaniel** [comment]
Wow you are fast!
